version: '3.4'

services:
  web-dev:
    stdin_open: true
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./:/app"
  web-prod:
    container_name: books-docker-prod
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
