version: '3.4'

services:
  web-dev:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
  web-prod:
    container_name: my-app-prod
    build: .
    ports:
      - '1337:80'
